server:
  port: 8080
  devtools.restart.enable: false

# logging.level:
#  root: INFO

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    hikari:
      # driver-class-name: org.h2.Driver
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:h2:../hsqldb/testdb;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      auto-commit: false
    tomcat.default-auto-commit: false
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.batch_size : 50
        order_inserts: true
        order_updates: true
        # show_sql: false
        # format_sql: false
        # use_sql_comments: false

decorator:
  datasource:
    p6spy:
      enable-logging: true
#      multiline: true
#      logging: slf4j
#      tracing:
#        include-parameter-values: true