server:
  port: 8080
  devtools.restart.enable: false

logging.level:
  root: INFO

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:../hsqldb/testdb
      username: sa
      password:
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    # properties:
    #  hibernate:
    #    show_sql: true
    #    format_sql: true
    #    use_sql_comments: true

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
      tracing:
        include-parameter-values: true